/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2_crysthel;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Crysthel
 */
public class Principal extends javax.swing.JFrame {

    adminProblemas admiP = new adminProblemas("./AdministrarProblemas.cbm");

    UsuarioNormal usuario_normal_actual;
    UsuarioAdministrador usuario_admin_actual;

    ArrayList<Usuarios> usuarios = new ArrayList();
    ArrayList<Problemas> problemas = new ArrayList();
    ArrayList<Respuestas> respuestas = new ArrayList();
    
    ArrayList<Publicaciones> publicacion = new ArrayList();
    ArrayList<Object> comentarios = new ArrayList();
    
    AdministradorUsuarioNormal adminUsuarioNormal = new AdministradorUsuarioNormal("./UsuarioNormal.cbm");
    AdministradorUsuarioAdmin adminUsuarioAdmin = new AdministradorUsuarioAdmin("./UsuarioAdministrador.cbm");
    admin_problemas adminProblemas = new admin_problemas("./AdministrarProblemas.bin");
    admin_comentarios adminComentarios = new admin_comentarios("./AdministrarComentarios.bin");
    admin_respuestas adminRespuestas = new admin_respuestas("./AdministrarRespuestas.bin");
    
    File Archivo;

    /**
     * Creates new form Principal
     */
    public Principal() {
        
        adminProblemas.cargarArchivo();
        adminProblemas.escribirArchivo();
        adminRespuestas.cargarArchivo();
        adminRespuestas.escribirArchivo();
        adminUsuarioAdmin.cargarArchivo();
        adminUsuarioAdmin.escrbirArchivo();
        adminUsuarioNormal.cargarArchivo();
        adminUsuarioNormal.escrbirArchivo();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_signup = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dt_fechaNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        tf_usuario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ps_contraseña = new javax.swing.JPasswordField();
        jLabel34 = new javax.swing.JLabel();
        rb_Administrador = new javax.swing.JRadioButton();
        rb_Normal = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        tf_correoElectronico = new javax.swing.JTextField();
        boton_registrarse = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        lb_fotopapeleta = new javax.swing.JLabel();
        bt_seleccionarimagen = new javax.swing.JButton();
        jd_login = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tf_usuarioLogIn = new javax.swing.JTextField();
        tf_contraseñaLogIn = new javax.swing.JTextField();
        bt_iniciarSesion = new javax.swing.JButton();
        jd_UsuarioAdministrador = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_usuariosGenerales = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        texta = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jd_UsuarioNormal = new javax.swing.JDialog();
        jTabbedPane6 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jt_solicitudes = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_info = new javax.swing.JTable();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jtree_solicitudesAmistad = new javax.swing.JTree();
        jScrollPane10 = new javax.swing.JScrollPane();
        jtree_listaAmigos = new javax.swing.JTree();
        jPanel5 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jScrollPane11 = new javax.swing.JScrollPane();
        jl_p = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        ta_mensaje = new javax.swing.JTextArea();
        bt_publico = new javax.swing.JRadioButton();
        bt_privado = new javax.swing.JRadioButton();
        bt_amigos = new javax.swing.JRadioButton();
        bt_problema = new javax.swing.JRadioButton();
        bt_repuestas = new javax.swing.JRadioButton();
        bt_comentario = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        bt_cerrado = new javax.swing.JRadioButton();
        bt_abierto = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        js_categoria = new javax.swing.JSpinner();
        jLabel17 = new javax.swing.JLabel();
        js_respuestas = new javax.swing.JSpinner();
        jScrollPane6 = new javax.swing.JScrollPane();
        ta_comentario = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        texta1 = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jd_about = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pp = new javax.swing.JPopupMenu();
        agregar = new javax.swing.JMenuItem();
        eliminar = new javax.swing.JMenuItem();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setText("Tu decides que Usuario Ser :D");

        jLabel2.setText("Nombre");

        jLabel8.setText("Fecha de Nacimento");

        jLabel10.setText("Usuario");

        jLabel11.setText("Contraseña");

        jLabel34.setText("Tipo de Usuario");

        rb_Administrador.setText("Administrador");

        rb_Normal.setText("Normal");
        rb_Normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_NormalActionPerformed(evt);
            }
        });

        jLabel4.setText("Correo Electronico");

        boton_registrarse.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boton_registrarse.setText("Registrar Usuario");
        boton_registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton_registrarseMouseClicked(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setText("Imagen:");

        lb_fotopapeleta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bt_seleccionarimagen.setText("Seleccionar Imagen");
        bt_seleccionarimagen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_seleccionarimagenMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_signupLayout = new javax.swing.GroupLayout(jd_signup.getContentPane());
        jd_signup.getContentPane().setLayout(jd_signupLayout);
        jd_signupLayout.setHorizontalGroup(
            jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signupLayout.createSequentialGroup()
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_signupLayout.createSequentialGroup()
                        .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_signupLayout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel34)
                                    .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel4))
                                    .addComponent(jLabel2))
                                .addGap(31, 31, 31)
                                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(dt_fechaNacimiento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ps_contraseña, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tf_correoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jd_signupLayout.createSequentialGroup()
                                            .addComponent(rb_Administrador)
                                            .addGap(18, 18, 18)
                                            .addComponent(rb_Normal)))
                                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_signupLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(bt_seleccionarimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lb_fotopapeleta, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signupLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(boton_registrarse)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signupLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(85, 85, 85))
        );
        jd_signupLayout.setVerticalGroup(
            jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_signupLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(23, 23, 23)
                .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signupLayout.createSequentialGroup()
                        .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(dt_fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(tf_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ps_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(rb_Administrador)
                            .addComponent(rb_Normal))
                        .addGap(24, 24, 24)
                        .addGroup(jd_signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tf_correoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lb_fotopapeleta, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_signupLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(bt_seleccionarimagen)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(boton_registrarse)
                .addGap(21, 21, 21))
        );

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Inicio de Sesion a mi Examen");

        jLabel5.setText("Usuario: ");

        jLabel7.setText("Contraseña:");

        bt_iniciarSesion.setText("Iniciar Sesion");
        bt_iniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_iniciarSesionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_usuarioLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                            .addComponent(tf_contraseñaLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(114, 114, 114))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(208, 208, 208))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(219, 219, 219)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bt_iniciarSesion)
                .addGap(28, 28, 28))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tf_usuarioLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_contraseñaLogIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(bt_iniciarSesion)
                .addContainerGap())
        );

        jt_usuariosGenerales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Correo", "Fecha", "Usuario", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(jt_usuariosGenerales);

        jLabel9.setText("Lista de usuarios en el sistema");

        texta.setColumns(20);
        texta.setRows(5);
        jScrollPane4.setViewportView(texta);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jLabel9)))
                .addContainerGap(355, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("1", jPanel1);

        jLabel12.setText("Publicaciones");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(jLabel12)
                .addContainerGap(706, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel12)
                .addContainerGap(499, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("2", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 901, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("3", jPanel3);

        jMenu3.setText("Administrador");

        jMenuItem5.setText("Abrir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Guardar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Salir");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("About");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jd_UsuarioAdministrador.setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout jd_UsuarioAdministradorLayout = new javax.swing.GroupLayout(jd_UsuarioAdministrador.getContentPane());
        jd_UsuarioAdministrador.getContentPane().setLayout(jd_UsuarioAdministradorLayout);
        jd_UsuarioAdministradorLayout.setHorizontalGroup(
            jd_UsuarioAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jd_UsuarioAdministradorLayout.setVerticalGroup(
            jd_UsuarioAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        jt_solicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Usuario"
            }
        ));
        jScrollPane7.setViewportView(jt_solicitudes);

        jButton4.setText("Agregar Amigos");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton4)
                .addContainerGap(709, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(166, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(148, 148, 148))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        jTabbedPane6.addTab("tab1", jPanel6);

        jt_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Correo", "Fecha", "Usuario", "Contraseña"
            }
        ));
        jScrollPane3.setViewportView(jt_info);

        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btnModificar)
                        .addGap(68, 68, 68)
                        .addComponent(btnEliminar)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("tab3", jPanel8);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Solicitudes de Amistad");
        jtree_solicitudesAmistad.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jtree_solicitudesAmistad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtree_solicitudesAmistadMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(jtree_solicitudesAmistad);

        treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lista de Amigos");
        jtree_listaAmigos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane10.setViewportView(jtree_listaAmigos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(70, 70, 70))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane6.addTab("tab4", jPanel4);

        jButton5.setText("ver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jl_p.setModel(new DefaultListModel()
        );
        jScrollPane11.setViewportView(jl_p);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 827, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane6.addTab("Ver publis", jPanel5);

        jLabel14.setText("ID");

        jLabel19.setText("mensaje");

        ta_mensaje.setColumns(20);
        ta_mensaje.setRows(5);
        jScrollPane8.setViewportView(ta_mensaje);

        buttonGroup2.add(bt_publico);
        bt_publico.setText("publico");

        buttonGroup2.add(bt_privado);
        bt_privado.setText("privado");

        buttonGroup2.add(bt_amigos);
        bt_amigos.setText("amigos");

        bt_problema.setText("problemas");

        bt_repuestas.setText("respuestas");

        bt_comentario.setText("comentarios");

        jLabel20.setText("estado");

        bt_cerrado.setSelected(true);
        bt_cerrado.setText("cerrado");

        bt_abierto.setText("abierto");

        jLabel16.setText("categoria");

        js_categoria.setModel(new javax.swing.SpinnerNumberModel(1, 1, 3, 1));

        jLabel17.setText("calificacion general");

        js_respuestas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        ta_comentario.setColumns(20);
        ta_comentario.setRows(5);
        jScrollPane6.setViewportView(ta_comentario);

        jButton3.setText("PUBLICAR");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19))
                .addGap(73, 73, 73)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_id)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(107, 107, 107)
                .addComponent(jButton3)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(js_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel16)
                                            .addGroup(jPanel7Layout.createSequentialGroup()
                                                .addComponent(bt_cerrado)
                                                .addGap(18, 18, 18)
                                                .addComponent(bt_abierto)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(js_respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17))))))
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(bt_problema)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_repuestas)
                        .addGap(187, 187, 187)
                        .addComponent(bt_comentario)
                        .addGap(42, 42, 42))))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap(740, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bt_publico)
                        .addComponent(bt_privado)
                        .addComponent(bt_amigos))
                    .addGap(46, 46, 46)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(tf_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_problema)
                    .addComponent(bt_comentario)
                    .addComponent(bt_repuestas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bt_cerrado)
                                    .addComponent(bt_abierto))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(js_respuestas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel7Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(bt_publico)
                    .addGap(33, 33, 33)
                    .addComponent(bt_privado)
                    .addGap(46, 46, 46)
                    .addComponent(bt_amigos)
                    .addContainerGap(188, Short.MAX_VALUE)))
        );

        jTabbedPane6.addTab("tab2", jPanel7);

        texta1.setColumns(20);
        texta1.setRows(5);
        jScrollPane5.setViewportView(texta1);

        jMenu1.setText("Normal");

        jMenuItem1.setText("Abrir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Guardar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Salir");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("About");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Publicaciones");

        jMenuItem9.setText("Hacer Publicaciones");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jd_UsuarioNormal.setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout jd_UsuarioNormalLayout = new javax.swing.GroupLayout(jd_UsuarioNormal.getContentPane());
        jd_UsuarioNormal.getContentPane().setLayout(jd_UsuarioNormalLayout);
        jd_UsuarioNormalLayout.setHorizontalGroup(
            jd_UsuarioNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioNormalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane6)
                .addContainerGap())
            .addGroup(jd_UsuarioNormalLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_UsuarioNormalLayout.setVerticalGroup(
            jd_UsuarioNormalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_UsuarioNormalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Es un mini proyecto xD\n");
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jd_aboutLayout = new javax.swing.GroupLayout(jd_about.getContentPane());
        jd_about.getContentPane().setLayout(jd_aboutLayout);
        jd_aboutLayout.setHorizontalGroup(
            jd_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_aboutLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_aboutLayout.setVerticalGroup(
            jd_aboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_aboutLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        agregar.setText("Agregar Amigos");
        agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMouseClicked(evt);
            }
        });
        pp.add(agregar);

        eliminar.setText("Eliminar Amigos");
        eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarMouseClicked(evt);
            }
        });
        pp.add(eliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Iniciar Sesion");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Crear una cuenta");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Bienvenido (a)! STACKOVERFLOW");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rb_NormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_NormalActionPerformed

    }//GEN-LAST:event_rb_NormalActionPerformed

    private void boton_registrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton_registrarseMouseClicked
        try {
            if (rb_Normal.isSelected()) {
                UsuarioNormal usuarioM = new UsuarioNormal(tf_nombre.getText(), tf_correoElectronico.getText(), dt_fechaNacimiento.getDate(),
                        tf_usuario.getText(), ps_contraseña.getText(), lb_fotopapeleta.getIcon(), false);
                adminUsuarioNormal.setUsuarioNormal(usuarioM);
                adminUsuarioNormal.escrbirArchivo();
                Image img = Toolkit.getDefaultToolkit().createImage("./default.jpeg").getScaledInstance(lb_fotopapeleta.getWidth(), lb_fotopapeleta.getHeight(), Image.SCALE_DEFAULT);
                lb_fotopapeleta.setIcon(new ImageIcon(img));
                JOptionPane.showMessageDialog(null, "Se ha guardado un USUARIO NORMAL. ");
                tf_nombre.setText("");
                tf_correoElectronico.setText("");
                tf_usuario.setText("");
                ps_contraseña.setText("");
            }
            if (rb_Administrador.isSelected()) {
                UsuarioAdministrador usuarioM = new UsuarioAdministrador(tf_nombre.getText(), tf_correoElectronico.getText(), dt_fechaNacimiento.getDate(),
                        tf_usuario.getText(), ps_contraseña.getText(), lb_fotopapeleta.getIcon(), false);
                adminUsuarioAdmin.setUsuarioAdmin(usuarioM);
                adminUsuarioAdmin.escrbirArchivo();
                Image img = Toolkit.getDefaultToolkit().createImage("./default.jpeg").getScaledInstance(lb_fotopapeleta.getWidth(), lb_fotopapeleta.getHeight(), Image.SCALE_DEFAULT);
                lb_fotopapeleta.setIcon(new ImageIcon(img));
                JOptionPane.showMessageDialog(null, "Se ha guardado un USUARIO ADMINISTRATIVO. ");
                tf_nombre.setText("");
                tf_correoElectronico.setText("");
                tf_usuario.setText("");
                ps_contraseña.setText("");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_boton_registrarseMouseClicked

    private void bt_seleccionarimagenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_seleccionarimagenMouseClicked

        try {
            JFileChooser fc = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jpeg", "gif");
            fc.setFileFilter(filtro);
            File archivo;
            int op = fc.showOpenDialog(this);
            if (op == JFileChooser.APPROVE_OPTION) {
                archivo = fc.getSelectedFile();
                Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(lb_fotopapeleta.getWidth(), lb_fotopapeleta.getHeight(), Image.SCALE_DEFAULT);
                this.lb_fotopapeleta.setIcon(new ImageIcon(img));
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_bt_seleccionarimagenMouseClicked

    private void bt_iniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_iniciarSesionMouseClicked
        DefaultTableModel modelo = (DefaultTableModel) jt_usuariosGenerales.getModel();
        DefaultTableModel modelo1 = (DefaultTableModel) jt_info.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) jt_solicitudes.getModel();

        for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
            if (tf_usuarioLogIn.getText().equals(adminUsuarioNormal.getUsuarioNormal().get(i).getNombreUsuario())) {
                if (tf_contraseñaLogIn.getText().equals(adminUsuarioNormal.getUsuarioNormal().get(i).getContraseña())) {
                    JOptionPane.showMessageDialog(this, "Bienvenido a mi Examen " + adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto());

                    jd_login.dispose();
                    modelo2.setRowCount(0);

                    for (int j = 0; j < adminUsuarioNormal.getUsuarioNormal().size(); j++) { //Que no se repita el nombre en jt
                        if (i != j) {
                            String[] newrow = {adminUsuarioNormal.getUsuarioNormal().get(j).getNombreCompleto(),
                                adminUsuarioNormal.getUsuarioNormal().get(j).getNombreUsuario()};
                            modelo2.addRow(newrow);
                            jt_solicitudes.setModel(modelo2);
                        }
                    }
                    modelo1.setRowCount(0);
                    String[] newrow = {adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto(), adminUsuarioNormal.getUsuarioNormal().get(i).getCorreoElectronico(),
                        adminUsuarioNormal.getUsuarioNormal().get(i).getFecha().toString(), adminUsuarioNormal.getUsuarioNormal().get(i).getNombreUsuario(),
                        adminUsuarioNormal.getUsuarioNormal().get(i).getContraseña()};
                    modelo1.addRow(newrow);

                    jt_info.setModel(modelo);
                    jd_UsuarioNormal.setModal(true);
                    jd_UsuarioNormal.pack();
                    jd_UsuarioNormal.setLocationRelativeTo(null);
                    jd_UsuarioNormal.setVisible(true);
                }
            }
        }
        for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
            for (int j = 0; j < adminUsuarioNormal.getUsuarioNormal().get(i).getSolicitudes().size(); j++) {
                if (adminUsuarioNormal.getUsuarioNormal().get(i).getNombreUsuario().equals(tf_usuarioLogIn.getText())) {
                    DefaultMutableTreeNode solicitud;
                    DefaultTreeModel modeloarbol = (DefaultTreeModel) jtree_solicitudesAmistad.getModel();
                    DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloarbol.getRoot();
                    solicitud = new DefaultMutableTreeNode(adminUsuarioNormal.getUsuarioNormal().get(i).getSolicitudes().get(j));
                    raiz.add(solicitud);
                    modeloarbol.reload();
                }
            }
        }
        for (int i = 0; i < adminUsuarioAdmin.getUsuarioAdmin().size(); i++) {
            if (tf_usuarioLogIn.getText().equals(adminUsuarioAdmin.getUsuarioAdmin().get(i).getNombreUsuario())) {     
                if (tf_contraseñaLogIn.getText().equals(adminUsuarioAdmin.getUsuarioAdmin().get(i).getContraseña())) {
                    JOptionPane.showMessageDialog(this, "Bienvenido al Sistema VIP (Administrativo) " + adminUsuarioAdmin.getUsuarioAdmin().get(i).getNombreCompleto());
                    modelo.setRowCount(0);
                    for (int j = 0; j < adminUsuarioNormal.getUsuarioNormal().size(); j++) {
                        String[] newrow = {adminUsuarioNormal.getUsuarioNormal().get(j).getNombreCompleto(), adminUsuarioNormal.getUsuarioNormal().get(j).getCorreoElectronico(),
                            adminUsuarioNormal.getUsuarioNormal().get(j).getFecha().toString(), adminUsuarioNormal.getUsuarioNormal().get(j).getNombreUsuario(),
                            adminUsuarioNormal.getUsuarioNormal().get(j).getContraseña()};
                        modelo.addRow(newrow);
                        jt_usuariosGenerales.setModel(modelo);
                    }
                    jd_login.dispose();
                    jd_UsuarioAdministrador.pack();
                    jd_UsuarioAdministrador.setModal(true);
                    jd_UsuarioAdministrador.setVisible(true);
                }
            }
        }
        tf_usuarioLogIn.setText("");
        tf_contraseñaLogIn.setText("");
    }//GEN-LAST:event_bt_iniciarSesionMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        jd_signup.setModal(true);
        jd_signup.pack();
        jd_signup.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jd_login.setModal(true);
        jd_login.pack();
        jd_login.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.jd_about.setModal(true);
        this.jd_about.pack();
        this.jd_about.setLocationRelativeTo(this);
        this.jd_about.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        texta1.setText("");
        try {
            JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto", "cbm");

            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);//Abrir archivo
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                fr = new FileReader(fichero);

                br = new BufferedReader(fr);
                String linea;
                texta.setText("");
                while ((linea = br.readLine()) != null) {

                    texta.append(linea);
                    texta.append("\n");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
      File Archivo;
        int cont = 0;
        String path = "";
        if (cont > 0) {
            Archivo = new File(path);
            FileOutputStream fw = null;
            ObjectOutputStream bw = null;
            try {
                fw = new FileOutputStream(Archivo);
                bw = new ObjectOutputStream(fw);
                for (Usuarios l : usuarios) {
                    bw.writeObject(l);
                }
                for (Publicaciones h : publicacion) {
                    bw.writeObject(h);
                }
                for (Respuestas s : respuestas) {
                    bw.writeObject(s);
                }
                for (Problemas ss : problemas) {
                    bw.writeObject(ss);
                }
                bw.flush();
            } catch (Exception ex) {
            } finally {
                try {
                    bw.close();
                    fw.close();
                } catch (Exception ex) {
                }
            }
        } else {
            JFileChooser fcs = new JFileChooser();
            int aprove = fcs.showSaveDialog(this);
            if (aprove == JFileChooser.APPROVE_OPTION) {
                File fs = fcs.getSelectedFile();
                path = fs.getAbsolutePath();
                FileOutputStream fw = null;
                ObjectOutputStream bw = null;
                try {
                    fw = new FileOutputStream(fs);
                    bw = new ObjectOutputStream(fw);
                    for (Usuarios l : usuarios) {
                        bw.writeObject(l);
                    }
                    for (Publicaciones h : publicacion) {
                        bw.writeObject(h);
                    }
                    for (Respuestas s : respuestas) {
                        bw.writeObject(s);
                    }
                    for (Problemas ss : problemas) {
                        bw.writeObject(ss);
                    }
                    bw.flush();
                } catch (Exception ex) {
                } finally {
                    try {
                        bw.close();
                        fw.close();
                    } catch (Exception ex) {
                    }
                }
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
         File Archivo;
        int cont = 0;
        String path = "";
        if (cont > 0) {
            Archivo = new File(path);
            FileOutputStream fw = null;
            ObjectOutputStream bw = null;
            try {
                fw = new FileOutputStream(Archivo);
                bw = new ObjectOutputStream(fw);
                for (Usuarios l : usuarios) {
                    bw.writeObject(l);
                }
                for (Publicaciones h : publicacion) {
                    bw.writeObject(h);
                }
                for (Respuestas s : respuestas) {
                    bw.writeObject(s);
                }
                for (Problemas ss : problemas) {
                    bw.writeObject(ss);
                }
                bw.flush();
            } catch (Exception ex) {
            } finally {
                try {
                    bw.close();
                    fw.close();
                } catch (Exception ex) {
                }
            }
        } else {
            JFileChooser fcs = new JFileChooser();
            int aprove = fcs.showSaveDialog(this);
            if (aprove == JFileChooser.APPROVE_OPTION) {
                File fs = fcs.getSelectedFile();
                path = fs.getAbsolutePath();
                FileOutputStream fw = null;
                ObjectOutputStream bw = null;
                try {
                    fw = new FileOutputStream(fs);
                    bw = new ObjectOutputStream(fw);
                    for (Usuarios l : usuarios) {
                        bw.writeObject(l);
                    }
                    for (Publicaciones h : publicacion) {
                        bw.writeObject(h);
                    }
                    for (Respuestas s : respuestas) {
                        bw.writeObject(s);
                    }
                    for (Problemas ss : problemas) {
                        bw.writeObject(ss);
                    }
                    bw.flush();
                } catch (Exception ex) {
                } finally {
                    try {
                        bw.close();
                        fw.close();
                    } catch (Exception ex) {
                    }
                }
            }
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        this.jd_about.setModal(true);
        this.jd_about.pack();
        this.jd_about.setLocationRelativeTo(this);
        this.jd_about.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        File fichero = null;
        FileReader fr = null;
        BufferedReader br = null;
        texta.setText("");
        try {
            JFileChooser jfc = new JFileChooser();
            FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de texto", "cbm");

            jfc.setFileFilter(filtro);
            int seleccion = jfc.showOpenDialog(this);//Abrir archivo
            if (seleccion == JFileChooser.APPROVE_OPTION) {
                fichero = jfc.getSelectedFile();
                fr = new FileReader(fichero);

                br = new BufferedReader(fr);
                String linea;
                texta.setText("");
                while ((linea = br.readLine()) != null) {

                    texta.append(linea);
                    texta.append("\n");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        try {
            br.close();
            fr.close();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
        try {
            if (jt_info.getSelectedRow() >= 0) {
                String nombreModificar = JOptionPane.showInputDialog(null, "Ingrese su nombre");
                DefaultTableModel modelo = (DefaultTableModel) jt_info.getModel();
                String nombre = JOptionPane.showInputDialog(null, "Ingrese el nuevo nombre a agregarse");
                String usuario = JOptionPane.showInputDialog(null, "Ingrese el nuevo nombre de usuario a agregarse");
                String correo = JOptionPane.showInputDialog(null, "Ingrese el nuevo correo de usuario a agregarse");
                String contra = JOptionPane.showInputDialog(null, "Ingrese la nueva contraseña de usuario");
                modelo.setValueAt(nombre, jt_info.getSelectedRow(), 0);
                modelo.setValueAt(correo, jt_info.getSelectedRow(), 1);
                modelo.setValueAt(usuario, jt_info.getSelectedRow(), 3);
                modelo.setValueAt(contra, jt_info.getSelectedRow(), 4);
                jt_info.setModel(modelo);
                adminUsuarioNormal.cargarArchivo();
                for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
                    if (adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto().equals(nombreModificar)) {
                        adminUsuarioNormal.getUsuarioNormal().get(i).setNombreCompleto(nombre);
                        adminUsuarioNormal.getUsuarioNormal().get(i).setCorreoElectronico(correo);
                        adminUsuarioNormal.getUsuarioNormal().get(i).setNombreUsuario(usuario);
                        adminUsuarioNormal.getUsuarioNormal().get(i).setContraseña(contra);
                    }
                }
                adminUsuarioNormal.escrbirArchivo();
                JOptionPane.showMessageDialog(null, "Se ha modificado el usuario correctamente. ");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        try {
            if (jt_info.getSelectedRow() >= 0) {
                DefaultTableModel modelo = (DefaultTableModel) jt_info.getModel();
                modelo.removeRow(jt_info.getSelectedRow());
                jt_info.setModel(modelo);
                adminUsuarioNormal.cargarArchivo();
                String nombreModificar = JOptionPane.showInputDialog(null, "Ingrese su nombre porfavor: ");
                for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
                    if (adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto().equals(nombreModificar)) {
                        adminUsuarioNormal.getUsuarioNormal().remove(i);
                    }
                }
                adminUsuarioNormal.escrbirArchivo();
                JOptionPane.showMessageDialog(null, "Se ha eliminado su usuario correctamente. ");
                jd_UsuarioNormal.dispose();
            }
        } catch (Exception e) {

        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        adminUsuarioNormal.cargarArchivo();
        String p = "";
        String estado;
        Date f = new Date();
        if (bt_problema.isSelected()) {
            if (bt_privado.isSelected()) {
                p = "privado";
            } else {
                if (bt_publico.isSelected()) {
                    p = "publico";
                } else {
                    p = "amigos";
                }
            }
            if (bt_cerrado.isSelected()) {
                estado = "cerrado";
            } else {
                estado = "abierto";
            }
            publicacion.add(new Problemas(estado, Integer.parseInt(js_categoria.getValue().toString()), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f));

            Problemas publi = new Problemas(estado, Integer.parseInt(js_categoria.getValue().toString()), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f);
            adminProblemas.cargarArchivo();

            adminProblemas.set_problemas(publi);
            adminProblemas.escribirArchivo();
            for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
                if (adminUsuarioNormal.getUsuarioNormal().get(i).equals(usuario_normal_actual)) {
                    adminUsuarioNormal.getUsuarioNormal().get(i).getPublicaciones().add(publi);
                }

            }

            JOptionPane.showMessageDialog(null, "Problema publicado");
        }
        if (bt_comentario.isSelected()) {

            if (bt_privado.isSelected()) {
                p = "privado";
            } else {
                if (bt_publico.isSelected()) {
                    p = "publico";
                } else {
                    p = "amigos";
                }

            }
            publicacion.add(new Comentarios(ta_comentario.getText(), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f));
            Comentarios comen = new Comentarios(ta_comentario.getText(), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f);
            adminComentarios ad1 = new adminComentarios("./comentarios.cbm");
            ad1.cargarArchivo();
            ad1.set_comentarios(comen);
            ad1.escribirArchivo();
            for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
                if (adminUsuarioNormal.getUsuarioNormal().get(i).equals(usuario_normal_actual)) {
                    adminUsuarioNormal.getUsuarioNormal().get(i).getPublicaciones().add(comen);
                }

            }
            JOptionPane.showMessageDialog(null, "Comentario publicado");
        }
        if (bt_repuestas.isSelected()) {
            if (bt_privado.isSelected()) {
                p = "privado";
            } else {
                if (bt_publico.isSelected()) {
                    p = "publico";
                } else {
                    p = "amigos";
                }

            }

            publicacion.add(new Respuestas(Integer.parseInt(js_respuestas.getValue().toString()), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f));
            Respuestas res = new Respuestas(Integer.parseInt(js_respuestas.getValue().toString()), tf_id.getText(), ta_mensaje.getText(), usuario_normal_actual, p, f);
            adminRespuestas.cargarArchivo();
            adminRespuestas.set_respuestas(res);
            adminRespuestas.escribirArchivo();

            for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
                if (adminUsuarioNormal.getUsuarioNormal().get(i).equals(usuario_normal_actual)) {
                    adminUsuarioNormal.getUsuarioNormal().get(i).getPublicaciones().add(res);
                }
            }
            JOptionPane.showMessageDialog(null, "respuestas publicado");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jtree_solicitudesAmistadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtree_solicitudesAmistadMouseClicked
        if (evt.isMetaDown()) {
            pp.show(jtree_solicitudesAmistad, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_jtree_solicitudesAmistadMouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        String agregar = JOptionPane.showInputDialog(null, "Ingrese el nombre de la persona a agregar: ");
        String nombre = JOptionPane.showInputDialog(null, "Ingrese su nombre porfavor: ");

        for (int i = 0; i < adminUsuarioNormal.getUsuarioNormal().size(); i++) {
            if (adminUsuarioNormal.getUsuarioNormal().get(i).getNombreCompleto().equals(nombre)) {
                adminUsuarioNormal.getUsuarioNormal().get(i).getSolicitudes().add(agregar);
                JOptionPane.showMessageDialog(null, "Solicitud de amistad enviada.");
            }
        }

    }//GEN-LAST:event_jButton4MouseClicked

    private void agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMouseClicked
        /*  if (evt.isMetaDown()) {
            int row = 
        }
         */
    }//GEN-LAST:event_agregarMouseClicked

    private void eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_eliminarMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultListModel model = (DefaultListModel) jl_p.getModel();
        model.removeAllElements();
        jl_p.setModel(model);
        admin_comentarios a = new admin_comentarios("./comentarios.cbm");
        a.cargarArchivo();
        admin_respuestas b = new admin_respuestas("./respuestas.cbm");
        b.cargarArchivo();
        admin_problemas c = new admin_problemas("./problemas.cbm");
        c.cargarArchivo();

        for (int i = 0; i < a.getListas_comentarios().size(); i++) {
            model.addElement(a.getListas_comentarios().get(i));
        }
        for (int i = 0; i < b.getListas_respuestas().size(); i++) {
            model.addElement(b.getListas_respuestas().get(i));
        }
        for (int i = 0; i < c.getListas_problemas().size(); i++) {
            model.addElement(c.getListas_problemas().get(i));
        }
        jl_p.setModel(model);

    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem agregar;
    private javax.swing.JButton boton_registrarse;
    private javax.swing.JRadioButton bt_abierto;
    private javax.swing.JRadioButton bt_amigos;
    private javax.swing.JRadioButton bt_cerrado;
    private javax.swing.JRadioButton bt_comentario;
    private javax.swing.JButton bt_iniciarSesion;
    private javax.swing.JRadioButton bt_privado;
    private javax.swing.JRadioButton bt_problema;
    private javax.swing.JRadioButton bt_publico;
    private javax.swing.JRadioButton bt_repuestas;
    private javax.swing.JButton bt_seleccionarimagen;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private com.toedter.calendar.JDateChooser dt_fechaNacimiento;
    private javax.swing.JMenuItem eliminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JDialog jd_UsuarioAdministrador;
    private javax.swing.JDialog jd_UsuarioNormal;
    private javax.swing.JDialog jd_about;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_signup;
    private javax.swing.JList<String> jl_p;
    private javax.swing.JSpinner js_categoria;
    private javax.swing.JSpinner js_respuestas;
    private javax.swing.JTable jt_info;
    private javax.swing.JTable jt_solicitudes;
    private javax.swing.JTable jt_usuariosGenerales;
    private javax.swing.JTree jtree_listaAmigos;
    private javax.swing.JTree jtree_solicitudesAmistad;
    private javax.swing.JLabel lb_fotopapeleta;
    private javax.swing.JPopupMenu pp;
    private javax.swing.JPasswordField ps_contraseña;
    private javax.swing.JRadioButton rb_Administrador;
    private javax.swing.JRadioButton rb_Normal;
    private javax.swing.JTextArea ta_comentario;
    private javax.swing.JTextArea ta_mensaje;
    private javax.swing.JTextArea texta;
    private javax.swing.JTextArea texta1;
    private javax.swing.JTextField tf_contraseñaLogIn;
    private javax.swing.JTextField tf_correoElectronico;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JTextField tf_usuarioLogIn;
    // End of variables declaration//GEN-END:variables

}
